# Generated by Django 5.2.2 on 2025-06-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'في الإنتظار'), ('confirmed', 'تم التأكيد'), ('completed', 'مكتمل'), ('cancelled', 'تم الإلغاء')], default='pending', max_length=20, verbose_name='الحالة')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='مسجّل في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_course', to='courses.course', verbose_name='الدورة')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_session', to='courses.coursesession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name_plural': 'التسجيلات',
            },
        ),
    ]
