# Generated by Django 5.2.2 on 2025-06-09 15:23

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفئة')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تم إنشاء الفئة في')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('location', models.CharField(blank=True, help_text='للحضوري', max_length=200, verbose_name='المكان')),
                ('meeting_link', models.URLField(blank=True, help_text='عبر الإنترنت', verbose_name='رابط اللقاء')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='المشاركين الحاليين')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='تم إلغاؤها')),
            ],
            options={
                'verbose_name_plural': 'جلسات الدورة',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('resources', models.URLField(blank=True, help_text='رابط إلى المصادر', verbose_name='المصادر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='طلب')),
            ],
            options={
                'verbose_name_plural': 'المشاريع',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('objectives', models.TextField(help_text='أهداف التدريب', verbose_name='أهداف الدورة')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الدورة')),
                ('duration_hours', models.PositiveIntegerField(help_text='ساعات مدة الدورة', verbose_name='مدة الدورة بالساعات')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للمشاركين')),
                ('min_participants', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للمشاركين')),
                ('delivery_mode', models.CharField(choices=[('online', 'على الإنترنت'), ('onsite', 'حضوريًا'), ('hybrid', 'مدمج')], max_length=20, verbose_name='طريقة تقديم الدورة التدريبية')),
                ('target_audience', models.CharField(choices=[('children', 'الأطفال (6-12 سنة)'), ('teens', 'المراهقون (13-17 سنة)'), ('adults', 'البالغون (18 عاماً فأكثر)'), ('seniors', 'كبار السن (55 سنة فأكثر)'), ('enterprise', 'الشركات')], max_length=20, verbose_name='الجمهور المستهدف للدورة')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'خبير')], max_length=20, verbose_name='مستوى صعوبة الدورة')),
                ('prerequisites', models.TextField(blank=True, help_text='المستوى المطلوب', verbose_name='المستوى المطلوب')),
                ('required_materials', models.TextField(blank=True, help_text='الأجهزة المطلوبة', verbose_name='الأجهزة المطلوبة')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('intro_video', models.URLField(blank=True, verbose_name='فيديو تمهيدي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_category', to='courses.category', verbose_name='فئة الدورة')),
            ],
            options={
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
            },
        ),
    ]
