# Generated by Django 5.2.2 on 2025-06-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught_instructor', to=settings.AUTH_USER_MODEL, verbose_name='مدرب الدورة'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_course', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_course', to='courses.course', verbose_name='الدورة'),
        ),
    ]
