# Generated by Django 5.2.2 on 2025-06-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'الفئة', 'verbose_name_plural': 'الفئات'},
        ),
    ]
