# Generated by Django 5.2.2 on 2025-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('suggestion_type', models.CharField(choices=[('general', 'التدريب العام'), ('custom', 'تدريب مخصص حسب الطلب'), ('private', 'التدريب الفردي')], max_length=20, verbose_name='نوع الاقتراح')),
                ('target_audience', models.CharField(blank=True, max_length=50, verbose_name='الجمهور المستهدف')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='المدة المقدرة بالساعات', null=True, verbose_name='المدة المقدَّرة')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمشاركين')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='نطاق الميزانية')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنتظار'), ('reviewing', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المشرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تم إنشاؤها في')),
            ],
            options={
                'verbose_name_plural': 'اقتراح دورة تدريبية',
            },
        ),
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('suggestion', 'اقتراح'), ('complaint', 'شكوى'), ('compliment', 'مدح'), ('bug_report', 'تبليغ عن خطأ')], max_length=20, verbose_name='نوع التعليقات')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم حلها')),
                ('admin_response', models.TextField(blank=True, verbose_name='رد المشرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تم إنشاؤها في')),
            ],
            options={
                'verbose_name_plural': 'التعليقات العامة',
            },
        ),
    ]
