# Generated by Django 5.2.2 on 2025-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'اقتراح'), ('complaint', 'شكوى'), ('compliment', 'شكر'), ('bug_report', 'تبليغ عن خطأ')], max_length=20, verbose_name='نوع التعليقات'),
        ),
    ]
