# Generated by Django 5.2.2 on 2025-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_generalfeedback_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfeedback',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
    ]
