# Generated by Django 5.2.2 on 2025-06-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_generalfeedback_is_validated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSuggestion',
        ),
    ]
