# Generated by Django 5.2.2 on 2025-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='أجر الساعة (د.ج)'),
        ),
    ]
