# Generated by Django 5.2.2 on 2025-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_instructorprofile_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_instructor_pending',
            field=models.BooleanField(default=False),
        ),
    ]
